export const REQUIRED_DIRECTORIES = [
  "content/sources",
  "content/notes",
  "content/inbox",
  "content/assets",
  "data",
  "artifacts/topics",
  "artifacts/reports",
  "artifacts/exports",
  "templates",
  "models/local",
  "models/cache",
  "runtime/init",
  "runtime/setup",
  "runtime/extensions",
  "runtime/jobs",
  "runtime/locks",
  "runtime/tmp",
  "runtime/logs",
  "runtime/config-history",
  "runtime/plans",
  "backups",
] as const;
