export const RESOURCE_PREFIXES = {
  workspace: "ws",
  setup: "stp",
  diagnostics: "diag",
  connection: "con",
  target: "ct",
  observation: "obs",
  scan: "scan",
  "change-batch": "cb",
  "change-item": "ci",
  "write-receipt": "wr",
  source: "src",
  snapshot: "snp",
  ingestion: "ing",
  document: "doc",
  revision: "rev",
  chunk: "chk",
  "vector-space": "vsp",
  provider: "prv",
  invocation: "inv",
  "vector-build": "vbr",
  evaluation: "eval",
  "index-generation": "igen",
  "graph-node": "gn",
  entity: "ent",
  relation: "rel",
  claim: "clm",
  evidence: "evd",
  reference: "gref",
  conflict: "cfs",
  generation: "ggen",
  extraction: "gex",
  retrieval: "ret",
  context: "ctx",
  answer: "ans",
  statement: "ast",
  citation: "cit",
  note: "note",
  topic: "top",
  "topic-snapshot": "tsp",
  synthesis: "syn",
  section: "sec",
  conclusion: "concl",
  "topic-citation": "tcit",
  "knowledge-gap": "gap",
  artifact: "art",
  build: "bld",
  export: "exp",
  model: "mdl",
  job: "job",
  plan: "plan",
  operation: "op",
  backup: "bkp",
  verification: "ver",
  event: "evt",
} as const;

export type ResourceName = keyof typeof RESOURCE_PREFIXES;
export type ResourceId<T extends ResourceName = ResourceName> = `${T}:${string}` & {
  readonly __resource: T;
};
