export const RESOURCE_PREFIXES = {
  workspace: "ws",
  setup: "stp",
  diagnostics: "diag",
  connection: "con",
  target: "ct",
  observation: "obs",
  scan: "scan",
  "change-batch": "cb",
  "change-item": "ci",
  "write-receipt": "wr",
  source: "src",
  snapshot: "snp",
  ingestion: "ing",
  document: "doc",
  revision: "rev",
  chunk: "chk",
  "vector-space": "vsp",
  "graph-node": "gn",
  entity: "ent",
  relation: "rel",
  claim: "clm",
  evidence: "evd",
  reference: "gref",
  conflict: "cfs",
  generation: "ggen",
  extraction: "gex",
  note: "note",
  topic: "top",
  section: "sec",
  artifact: "art",
  build: "bld",
  model: "mdl",
  job: "job",
  plan: "plan",
  operation: "op",
  backup: "bkp",
  event: "evt",
} as const;

export type ResourceName = keyof typeof RESOURCE_PREFIXES;
export type ResourceId<T extends ResourceName = ResourceName> = `${T}:${string}` & {
  readonly __resource: T;
};
